### PR TITLE
Add blocks header

### PR DESCRIPTION
**Pull request by nathanielcwm**

### CODE REVIEW

**Comment by barton2526** [comment]
Who is the creator of this image?

**Comment by nathanielcwm** [comment]
Joshoeah it's currently used on gridcoin.us as a header.

The vectors were traced by me.

**Comment by barton2526** [comment]
This repository is licensed as CC0 (public domain).  You will need to get his permission to place it here.

**Comment by nathanielcwm** [comment]
So CC0 is incompatible with CC BY-SA without explicit permission from the creator?

**Comment by nathanielcwm** [comment]
It appears that my traced version fits under adaptation and as such can have the license changed to CC0.

**Comment by barton2526** [comment]
> 
> 
> It appears that my traced version fits under adaptation and as such can have the license changed to CC0.

No.  I suggest you do some reading on the legal definition of adapting works (https://creativecommons.org/faq/#what-is-an-adaptation).  You did not meaningfully change the art in any way, you just changed it to a vector file...

**Pull request closed without merging**
